# Generated by Django 4.2.9 on 2026-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=255, null=True)),
                ('customerName', models.CharField(blank=True, max_length=255, null=True)),
                ('contactName', models.CharField(blank=True, max_length=255, null=True)),
                ('contactNo', models.CharField(blank=True, max_length=20, null=True)),
                ('itemNo', models.CharField(blank=True, max_length=100, null=True)),
                ('custId', models.CharField(blank=True, max_length=100, null=True)),
                ('estimatedSalesPrice', models.FloatField(default=0)),
                ('nominatedPrice', models.FloatField(default=0)),
                ('creationDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
