# Generated by Django 4.2.9 on 2026-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_creation', '0003_alter_itemcard_base_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(db_column='type', max_length=100)),
                ('item_category_code', models.CharField(db_column='item_category_code', max_length=50, null=True)),
                ('costing_method', models.CharField(db_column='costing_method', max_length=50, null=True)),
                ('inventory_posting_group', models.CharField(db_column='inventory_posting_group', max_length=50, null=True)),
                ('price_profit_calculation', models.CharField(db_column='price_profit_calculation', max_length=50, null=True)),
                ('gen_prod_posting_group', models.CharField(db_column='gen_prod_posting_group', max_length=50, null=True)),
                ('replenishment_system', models.CharField(db_column='replenishment_system', max_length=50, null=True)),
                ('qc_applicable', models.CharField(db_column='qc_applicable', max_length=50, null=True)),
                ('manufacturing_policy', models.CharField(db_column='manufacturing_policy', max_length=50, null=True)),
                ('assembly_policy', models.CharField(db_column='assembly_policy', max_length=50, null=True)),
                ('reordering_policy', models.CharField(db_column='reordering_policy', max_length=50, null=True)),
                ('include_inventory', models.CharField(db_column='include_inventory', max_length=50, null=True)),
                ('gst_credit', models.CharField(db_column='gst_credit', max_length=50, null=True)),
                ('flushing_method', models.CharField(db_column='flushing_method', max_length=50, null=True)),
                ('template_applied', models.CharField(db_column='template_applied', max_length=100, null=True)),
                ('rounding_precision', models.CharField(db_column='rounding_precision', max_length=50, null=True)),
                ('gst_group_code', models.CharField(db_column='gst_group_code', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_applytemplate',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='itemcard',
            options={'managed': False},
        ),
    ]
