# Generated by Django 4.2.9 on 2026-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_creation', '0004_applytemplate_delete_itemcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
