# Generated by Django 4.2.9 on 2026-03-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_creation', '0004_applytemplate_alter_itemcard_options'),
        ('item_creation', '0006_item_assembly_policy_item_base_unit_of_measure_and_more'),
    ]

    operations = [
    ]
